name: Intel Spark Bench

on:
  pull_request

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tpcds-bench:
    runs-on: sr614-self-hosted
    steps:
      - uses: actions/checkout@v2
      #- name: Set up JDK 1.8
      #  uses: actions/setup-java@v2
      #  with:
      #    distribution: 'zulu'
      #    java-version: '8.0.345'
      #    java-package: jdk
      #    check-latest: false
      #    overwrite-settings: false
      - run: sudo swapoff -a
      - run: free
      - name: Build Spark
        run: |
          git clean -dfx
          JAVA_HOME=/home/sparkuser/jdk1.8.0_161
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          #mvn clean package -Phadoop-3 -Dhadoop.version=3.3.1 -Phive -Phive-thriftserver -Pyarn
          ./dev/make-distribution.sh --name spark_${PR_NUMBER} --tgz -Phadoop-3 -Dhadoop.version=3.3.1 -Phive -Phive-thriftserver -Pyarn
          cp spark*tgz /home/sparkuser/archieve
          rm -rf /home/sparkuser/tpcds/spark && mkdir -p /home/sparkuser/tpcds/spark && tar xf spark*tgz -C /home/sparkuser/tpcds/spark --strip-components=1
          cp /home/sparkuser/spark-331/conf/spark-defaults.conf /home/sparkuser/tpcds/spark/conf
      - name: Run TPCDS
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          cd /home/sparkuser/tpcds/test
          bash tpcds_spark.sh pr_${PR_NUMBER}
